web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/code
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  external_links:
    - mydb
php:
  build: .
  volumes:
    - ./code:/code
    - ./docker_conf/php:/usr/local/etc/php/conf.d
