mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - "3306:3306"
web:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./code:/code
    - ./default.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    - mysql
php:
  build: .
  volumes:
    - ./code:/code
    - ./docker_conf/php:/usr/local/etc/php/conf.d
